# Generated by Django 4.2.1 on 2023-06-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
            preserve_default=False,
        )
    ]
